// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fafdvwacojjupvvsydvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZmR2d2Fjb2pqdXB2dnN5ZHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjQ5NDcsImV4cCI6MjA3MzIwMDk0N30.9Ek6K7piwLu3e_4AHZiphz-qJK4q0sSo30V5foWZ3j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});